platform :ios, '9.0'
use_frameworks!

target 'NetworkingDemo' do
    pod 'Alamofire', '4.5.0'
    pod 'CocoaLumberjack/Swift', '3.1.0'
    pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :tag => '4.0.0-alpha.0'
end
